name: 'Publish'
description: 'Publish images'
runs:
  using: "composite"
  steps:

    - run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
        DATE=$(date -u +%Y%m%d%H%M%S)
        TAG_VERSION=$DATE
        IMAGENAME="initial-java-spring"
        cd app/default-spring
        docker build \
          --file ./Dockerfile \
          --no-cache=true \
          -t ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION} .
        docker tag ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION} ${{ env.REGISTRY }}/${IMAGENAME}:latest
        docker push ${{ env.REGISTRY }}/${IMAGENAME}:${TAG_VERSION}
        docker push ${{ env.REGISTRY }}/${IMAGENAME}:latest
        cd ../../
        
      shell: bash