---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sulimann-templates
spec:
  type: url
  targets:
    - https://github.com/rafaelsulimann/backstage/blob/main/templates/golang.yaml
    - https://github.com/rafaelsulimann/backstage/blob/main/templates/create-git-repo-org.yaml
