name: 'Deploy'
description: 'Deploy application'
inputs:
  app_version:
    description: 'Application version'
    required: true
runs:
  using: "composite"
  steps:

    - run: |
        cd app/deployment/k8s/default-spring
        helm upgrade --install ${{ values.name }} ./ \
        --set=image.repository=ghrc.io/sulimanns/${{ values.name }} \
        --set=service.port=8080 \
        --set=image.tag=${{ inputs.app_version }}
        
      shell: bash